//DECLARACION Y TIPOS DE VARIABLES
//ES POSIBLE REDEFINIR O REDECLARAR VARIABLES CON var
//PROCURAR USAR SIEMPRE let

//let
//DECLARACION DE VARIABLE
let koder;

//ASIGNACION DE VALOR
koder='Lalo'

//INICIALIZACION-----DECLARAR Y AIGNAR VALOR A LA VARIABLE
let koder2='Mauricio'

//Hoisting-----PROCESO O METODOLOGIAS 

